/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var v2ray_com_core_common_protocol_user_pb = require('../../../../../v2ray.com/core/common/protocol/user_pb.js');
var v2ray_com_core_common_serial_typed_message_pb = require('../../../../../v2ray.com/core/common/serial/typed_message_pb.js');
var v2ray_com_core_config_pb = require('../../../../../v2ray.com/core/config_pb.js');
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AddInboundRequest', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AddInboundResponse', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AddOutboundRequest', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AddOutboundResponse', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AddUserOperation', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AlterInboundRequest', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AlterInboundResponse', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AlterOutboundRequest', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.AlterOutboundResponse', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.Config', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.RemoveInboundRequest', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.RemoveInboundResponse', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse', null, global);
goog.exportSymbol('proto.v2ray.core.app.proxyman.command.RemoveUserOperation', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AddUserOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AddUserOperation.displayName = 'proto.v2ray.core.app.proxyman.command.AddUserOperation';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AddUserOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AddUserOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    user: (f = msg.getUser()) && v2ray_com_core_common_protocol_user_pb.User.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AddUserOperation}
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AddUserOperation;
  return proto.v2ray.core.app.proxyman.command.AddUserOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AddUserOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AddUserOperation}
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v2ray_com_core_common_protocol_user_pb.User;
      reader.readMessage(value,v2ray_com_core_common_protocol_user_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AddUserOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AddUserOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v2ray_com_core_common_protocol_user_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * optional v2ray.core.common.protocol.User user = 1;
 * @return {?proto.v2ray.core.common.protocol.User}
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.prototype.getUser = function() {
  return /** @type{?proto.v2ray.core.common.protocol.User} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_protocol_user_pb.User, 1));
};


/** @param {?proto.v2ray.core.common.protocol.User|undefined} value */
proto.v2ray.core.app.proxyman.command.AddUserOperation.prototype.setUser = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.v2ray.core.app.proxyman.command.AddUserOperation.prototype.clearUser = function() {
  this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.app.proxyman.command.AddUserOperation.prototype.hasUser = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.RemoveUserOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.RemoveUserOperation.displayName = 'proto.v2ray.core.app.proxyman.command.RemoveUserOperation';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.RemoveUserOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveUserOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    email: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveUserOperation}
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.RemoveUserOperation;
  return proto.v2ray.core.app.proxyman.command.RemoveUserOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveUserOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveUserOperation}
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.RemoveUserOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveUserOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string email = 1;
 * @return {string}
 */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.app.proxyman.command.RemoveUserOperation.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AddInboundRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AddInboundRequest.displayName = 'proto.v2ray.core.app.proxyman.command.AddInboundRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AddInboundRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AddInboundRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    inbound: (f = msg.getInbound()) && v2ray_com_core_config_pb.InboundHandlerConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AddInboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AddInboundRequest;
  return proto.v2ray.core.app.proxyman.command.AddInboundRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AddInboundRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AddInboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v2ray_com_core_config_pb.InboundHandlerConfig;
      reader.readMessage(value,v2ray_com_core_config_pb.InboundHandlerConfig.deserializeBinaryFromReader);
      msg.setInbound(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AddInboundRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AddInboundRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInbound();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v2ray_com_core_config_pb.InboundHandlerConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional v2ray.core.InboundHandlerConfig inbound = 1;
 * @return {?proto.v2ray.core.InboundHandlerConfig}
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.prototype.getInbound = function() {
  return /** @type{?proto.v2ray.core.InboundHandlerConfig} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_config_pb.InboundHandlerConfig, 1));
};


/** @param {?proto.v2ray.core.InboundHandlerConfig|undefined} value */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.prototype.setInbound = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.v2ray.core.app.proxyman.command.AddInboundRequest.prototype.clearInbound = function() {
  this.setInbound(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.app.proxyman.command.AddInboundRequest.prototype.hasInbound = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AddInboundResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AddInboundResponse.displayName = 'proto.v2ray.core.app.proxyman.command.AddInboundResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AddInboundResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AddInboundResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AddInboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AddInboundResponse;
  return proto.v2ray.core.app.proxyman.command.AddInboundResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AddInboundResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AddInboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AddInboundResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AddInboundResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddInboundResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.RemoveInboundRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.displayName = 'proto.v2ray.core.app.proxyman.command.RemoveInboundRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveInboundRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveInboundRequest}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.RemoveInboundRequest;
  return proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveInboundRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveInboundRequest}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveInboundRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.app.proxyman.command.RemoveInboundRequest.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.RemoveInboundResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.displayName = 'proto.v2ray.core.app.proxyman.command.RemoveInboundResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveInboundResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveInboundResponse}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.RemoveInboundResponse;
  return proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveInboundResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveInboundResponse}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveInboundResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveInboundResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AlterInboundRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AlterInboundRequest.displayName = 'proto.v2ray.core.app.proxyman.command.AlterInboundRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AlterInboundRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AlterInboundRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operation: (f = msg.getOperation()) && v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterInboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AlterInboundRequest;
  return proto.v2ray.core.app.proxyman.command.AlterInboundRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterInboundRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterInboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 2:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.setOperation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AlterInboundRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterInboundRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional v2ray.core.common.serial.TypedMessage operation = 2;
 * @return {?proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.getOperation = function() {
  return /** @type{?proto.v2ray.core.common.serial.TypedMessage} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 2));
};


/** @param {?proto.v2ray.core.common.serial.TypedMessage|undefined} value */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.setOperation = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.clearOperation = function() {
  this.setOperation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundRequest.prototype.hasOperation = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AlterInboundResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AlterInboundResponse.displayName = 'proto.v2ray.core.app.proxyman.command.AlterInboundResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AlterInboundResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AlterInboundResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterInboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AlterInboundResponse;
  return proto.v2ray.core.app.proxyman.command.AlterInboundResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterInboundResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterInboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AlterInboundResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterInboundResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterInboundResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AddOutboundRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AddOutboundRequest.displayName = 'proto.v2ray.core.app.proxyman.command.AddOutboundRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AddOutboundRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AddOutboundRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    outbound: (f = msg.getOutbound()) && v2ray_com_core_config_pb.OutboundHandlerConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AddOutboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AddOutboundRequest;
  return proto.v2ray.core.app.proxyman.command.AddOutboundRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AddOutboundRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AddOutboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v2ray_com_core_config_pb.OutboundHandlerConfig;
      reader.readMessage(value,v2ray_com_core_config_pb.OutboundHandlerConfig.deserializeBinaryFromReader);
      msg.setOutbound(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AddOutboundRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AddOutboundRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOutbound();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v2ray_com_core_config_pb.OutboundHandlerConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional v2ray.core.OutboundHandlerConfig outbound = 1;
 * @return {?proto.v2ray.core.OutboundHandlerConfig}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.prototype.getOutbound = function() {
  return /** @type{?proto.v2ray.core.OutboundHandlerConfig} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_config_pb.OutboundHandlerConfig, 1));
};


/** @param {?proto.v2ray.core.OutboundHandlerConfig|undefined} value */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.prototype.setOutbound = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.v2ray.core.app.proxyman.command.AddOutboundRequest.prototype.clearOutbound = function() {
  this.setOutbound(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundRequest.prototype.hasOutbound = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AddOutboundResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AddOutboundResponse.displayName = 'proto.v2ray.core.app.proxyman.command.AddOutboundResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AddOutboundResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AddOutboundResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AddOutboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AddOutboundResponse;
  return proto.v2ray.core.app.proxyman.command.AddOutboundResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AddOutboundResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AddOutboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AddOutboundResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AddOutboundResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AddOutboundResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.displayName = 'proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest;
  return proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.app.proxyman.command.RemoveOutboundRequest.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.displayName = 'proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse;
  return proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.RemoveOutboundResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AlterOutboundRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.displayName = 'proto.v2ray.core.app.proxyman.command.AlterOutboundRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AlterOutboundRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operation: (f = msg.getOperation()) && v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterOutboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AlterOutboundRequest;
  return proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterOutboundRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterOutboundRequest}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 2:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.setOperation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterOutboundRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional v2ray.core.common.serial.TypedMessage operation = 2;
 * @return {?proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.getOperation = function() {
  return /** @type{?proto.v2ray.core.common.serial.TypedMessage} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 2));
};


/** @param {?proto.v2ray.core.common.serial.TypedMessage|undefined} value */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.setOperation = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.clearOperation = function() {
  this.setOperation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundRequest.prototype.hasOperation = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.AlterOutboundResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.displayName = 'proto.v2ray.core.app.proxyman.command.AlterOutboundResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.AlterOutboundResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterOutboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.AlterOutboundResponse;
  return proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterOutboundResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.AlterOutboundResponse}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.AlterOutboundResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.AlterOutboundResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.app.proxyman.command.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.app.proxyman.command.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.app.proxyman.command.Config.displayName = 'proto.v2ray.core.app.proxyman.command.Config';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.app.proxyman.command.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.app.proxyman.command.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.app.proxyman.command.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.Config.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.app.proxyman.command.Config}
 */
proto.v2ray.core.app.proxyman.command.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.app.proxyman.command.Config;
  return proto.v2ray.core.app.proxyman.command.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.app.proxyman.command.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.app.proxyman.command.Config}
 */
proto.v2ray.core.app.proxyman.command.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.app.proxyman.command.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.app.proxyman.command.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.app.proxyman.command.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.app.proxyman.command.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.v2ray.core.app.proxyman.command);
