/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var v2ray_com_core_common_serial_typed_message_pb = require('../../v2ray.com/core/common/serial/typed_message_pb.js');
var v2ray_com_core_transport_config_pb = require('../../v2ray.com/core/transport/config_pb.js');
goog.exportSymbol('proto.v2ray.core.Config', null, global);
goog.exportSymbol('proto.v2ray.core.InboundHandlerConfig', null, global);
goog.exportSymbol('proto.v2ray.core.OutboundHandlerConfig', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v2ray.core.Config.repeatedFields_, null);
};
goog.inherits(proto.v2ray.core.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.Config.displayName = 'proto.v2ray.core.Config';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v2ray.core.Config.repeatedFields_ = [1,2,4,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    inboundList: jspb.Message.toObjectList(msg.getInboundList(),
    proto.v2ray.core.InboundHandlerConfig.toObject, includeInstance),
    outboundList: jspb.Message.toObjectList(msg.getOutboundList(),
    proto.v2ray.core.OutboundHandlerConfig.toObject, includeInstance),
    appList: jspb.Message.toObjectList(msg.getAppList(),
    v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject, includeInstance),
    transport: (f = msg.getTransport()) && v2ray_com_core_transport_config_pb.Config.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.Config}
 */
proto.v2ray.core.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.Config;
  return proto.v2ray.core.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.Config}
 */
proto.v2ray.core.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.v2ray.core.InboundHandlerConfig;
      reader.readMessage(value,proto.v2ray.core.InboundHandlerConfig.deserializeBinaryFromReader);
      msg.addInbound(value);
      break;
    case 2:
      var value = new proto.v2ray.core.OutboundHandlerConfig;
      reader.readMessage(value,proto.v2ray.core.OutboundHandlerConfig.deserializeBinaryFromReader);
      msg.addOutbound(value);
      break;
    case 4:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.addApp(value);
      break;
    case 5:
      var value = new v2ray_com_core_transport_config_pb.Config;
      reader.readMessage(value,v2ray_com_core_transport_config_pb.Config.deserializeBinaryFromReader);
      msg.setTransport(value);
      break;
    case 6:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInboundList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.v2ray.core.InboundHandlerConfig.serializeBinaryToWriter
    );
  }
  f = message.getOutboundList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.v2ray.core.OutboundHandlerConfig.serializeBinaryToWriter
    );
  }
  f = message.getAppList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
  f = message.getTransport();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      v2ray_com_core_transport_config_pb.Config.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
};


/**
 * repeated InboundHandlerConfig inbound = 1;
 * @return {!Array.<!proto.v2ray.core.InboundHandlerConfig>}
 */
proto.v2ray.core.Config.prototype.getInboundList = function() {
  return /** @type{!Array.<!proto.v2ray.core.InboundHandlerConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.v2ray.core.InboundHandlerConfig, 1));
};


/** @param {!Array.<!proto.v2ray.core.InboundHandlerConfig>} value */
proto.v2ray.core.Config.prototype.setInboundList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.v2ray.core.InboundHandlerConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v2ray.core.InboundHandlerConfig}
 */
proto.v2ray.core.Config.prototype.addInbound = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.v2ray.core.InboundHandlerConfig, opt_index);
};


proto.v2ray.core.Config.prototype.clearInboundList = function() {
  this.setInboundList([]);
};


/**
 * repeated OutboundHandlerConfig outbound = 2;
 * @return {!Array.<!proto.v2ray.core.OutboundHandlerConfig>}
 */
proto.v2ray.core.Config.prototype.getOutboundList = function() {
  return /** @type{!Array.<!proto.v2ray.core.OutboundHandlerConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.v2ray.core.OutboundHandlerConfig, 2));
};


/** @param {!Array.<!proto.v2ray.core.OutboundHandlerConfig>} value */
proto.v2ray.core.Config.prototype.setOutboundList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.v2ray.core.OutboundHandlerConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v2ray.core.OutboundHandlerConfig}
 */
proto.v2ray.core.Config.prototype.addOutbound = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.v2ray.core.OutboundHandlerConfig, opt_index);
};


proto.v2ray.core.Config.prototype.clearOutboundList = function() {
  this.setOutboundList([]);
};


/**
 * repeated common.serial.TypedMessage app = 4;
 * @return {!Array.<!proto.v2ray.core.common.serial.TypedMessage>}
 */
proto.v2ray.core.Config.prototype.getAppList = function() {
  return /** @type{!Array.<!proto.v2ray.core.common.serial.TypedMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 4));
};


/** @param {!Array.<!proto.v2ray.core.common.serial.TypedMessage>} value */
proto.v2ray.core.Config.prototype.setAppList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.v2ray.core.common.serial.TypedMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.Config.prototype.addApp = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.v2ray.core.common.serial.TypedMessage, opt_index);
};


proto.v2ray.core.Config.prototype.clearAppList = function() {
  this.setAppList([]);
};


/**
 * optional transport.Config transport = 5;
 * @return {?proto.v2ray.core.transport.Config}
 */
proto.v2ray.core.Config.prototype.getTransport = function() {
  return /** @type{?proto.v2ray.core.transport.Config} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_transport_config_pb.Config, 5));
};


/** @param {?proto.v2ray.core.transport.Config|undefined} value */
proto.v2ray.core.Config.prototype.setTransport = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.v2ray.core.Config.prototype.clearTransport = function() {
  this.setTransport(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.Config.prototype.hasTransport = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated common.serial.TypedMessage extension = 6;
 * @return {!Array.<!proto.v2ray.core.common.serial.TypedMessage>}
 */
proto.v2ray.core.Config.prototype.getExtensionList = function() {
  return /** @type{!Array.<!proto.v2ray.core.common.serial.TypedMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 6));
};


/** @param {!Array.<!proto.v2ray.core.common.serial.TypedMessage>} value */
proto.v2ray.core.Config.prototype.setExtensionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.v2ray.core.common.serial.TypedMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.Config.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.v2ray.core.common.serial.TypedMessage, opt_index);
};


proto.v2ray.core.Config.prototype.clearExtensionList = function() {
  this.setExtensionList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.InboundHandlerConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.InboundHandlerConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.InboundHandlerConfig.displayName = 'proto.v2ray.core.InboundHandlerConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.InboundHandlerConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.InboundHandlerConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.InboundHandlerConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, ""),
    receiverSettings: (f = msg.getReceiverSettings()) && v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject(includeInstance, f),
    proxySettings: (f = msg.getProxySettings()) && v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.InboundHandlerConfig}
 */
proto.v2ray.core.InboundHandlerConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.InboundHandlerConfig;
  return proto.v2ray.core.InboundHandlerConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.InboundHandlerConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.InboundHandlerConfig}
 */
proto.v2ray.core.InboundHandlerConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 2:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.setReceiverSettings(value);
      break;
    case 3:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.setProxySettings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.InboundHandlerConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.InboundHandlerConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.InboundHandlerConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReceiverSettings();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
  f = message.getProxySettings();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.InboundHandlerConfig.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional common.serial.TypedMessage receiver_settings = 2;
 * @return {?proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.getReceiverSettings = function() {
  return /** @type{?proto.v2ray.core.common.serial.TypedMessage} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 2));
};


/** @param {?proto.v2ray.core.common.serial.TypedMessage|undefined} value */
proto.v2ray.core.InboundHandlerConfig.prototype.setReceiverSettings = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.v2ray.core.InboundHandlerConfig.prototype.clearReceiverSettings = function() {
  this.setReceiverSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.hasReceiverSettings = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.serial.TypedMessage proxy_settings = 3;
 * @return {?proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.getProxySettings = function() {
  return /** @type{?proto.v2ray.core.common.serial.TypedMessage} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 3));
};


/** @param {?proto.v2ray.core.common.serial.TypedMessage|undefined} value */
proto.v2ray.core.InboundHandlerConfig.prototype.setProxySettings = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.v2ray.core.InboundHandlerConfig.prototype.clearProxySettings = function() {
  this.setProxySettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.InboundHandlerConfig.prototype.hasProxySettings = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v2ray.core.OutboundHandlerConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v2ray.core.OutboundHandlerConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.v2ray.core.OutboundHandlerConfig.displayName = 'proto.v2ray.core.OutboundHandlerConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.v2ray.core.OutboundHandlerConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v2ray.core.OutboundHandlerConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.OutboundHandlerConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, ""),
    senderSettings: (f = msg.getSenderSettings()) && v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject(includeInstance, f),
    proxySettings: (f = msg.getProxySettings()) && v2ray_com_core_common_serial_typed_message_pb.TypedMessage.toObject(includeInstance, f),
    expire: jspb.Message.getFieldWithDefault(msg, 4, 0),
    comment: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v2ray.core.OutboundHandlerConfig}
 */
proto.v2ray.core.OutboundHandlerConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v2ray.core.OutboundHandlerConfig;
  return proto.v2ray.core.OutboundHandlerConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v2ray.core.OutboundHandlerConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v2ray.core.OutboundHandlerConfig}
 */
proto.v2ray.core.OutboundHandlerConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 2:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.setSenderSettings(value);
      break;
    case 3:
      var value = new v2ray_com_core_common_serial_typed_message_pb.TypedMessage;
      reader.readMessage(value,v2ray_com_core_common_serial_typed_message_pb.TypedMessage.deserializeBinaryFromReader);
      msg.setProxySettings(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpire(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v2ray.core.OutboundHandlerConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v2ray.core.OutboundHandlerConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v2ray.core.OutboundHandlerConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSenderSettings();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
  f = message.getProxySettings();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      v2ray_com_core_common_serial_typed_message_pb.TypedMessage.serializeBinaryToWriter
    );
  }
  f = message.getExpire();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getComment();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.v2ray.core.OutboundHandlerConfig.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional common.serial.TypedMessage sender_settings = 2;
 * @return {?proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.getSenderSettings = function() {
  return /** @type{?proto.v2ray.core.common.serial.TypedMessage} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 2));
};


/** @param {?proto.v2ray.core.common.serial.TypedMessage|undefined} value */
proto.v2ray.core.OutboundHandlerConfig.prototype.setSenderSettings = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.v2ray.core.OutboundHandlerConfig.prototype.clearSenderSettings = function() {
  this.setSenderSettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.hasSenderSettings = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.serial.TypedMessage proxy_settings = 3;
 * @return {?proto.v2ray.core.common.serial.TypedMessage}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.getProxySettings = function() {
  return /** @type{?proto.v2ray.core.common.serial.TypedMessage} */ (
    jspb.Message.getWrapperField(this, v2ray_com_core_common_serial_typed_message_pb.TypedMessage, 3));
};


/** @param {?proto.v2ray.core.common.serial.TypedMessage|undefined} value */
proto.v2ray.core.OutboundHandlerConfig.prototype.setProxySettings = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.v2ray.core.OutboundHandlerConfig.prototype.clearProxySettings = function() {
  this.setProxySettings(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.hasProxySettings = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 expire = 4;
 * @return {number}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.getExpire = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.v2ray.core.OutboundHandlerConfig.prototype.setExpire = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string comment = 5;
 * @return {string}
 */
proto.v2ray.core.OutboundHandlerConfig.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.v2ray.core.OutboundHandlerConfig.prototype.setComment = function(value) {
  jspb.Message.setField(this, 5, value);
};


goog.object.extend(exports, proto.v2ray.core);
